add fesapi (RESQML) to CMakeLists
GEOSX/thirdPartyLibs pull request #202
Opened 2022-10-04 07:57 UTC by untereiner

2022-10-04 09:00 UTC, untereiner commented
Where can I enable the ENABLE_FESAPI flag to the CI to compile it ?

2022-10-04 17:36 UTC, klevzoff approved these changes
LGTM!

2022-10-04 17:36 UTC, klevzoff commented on CMakeLists.txt
> +                        DEPENDS ${HDF5_DEPENDENCIES} minizip
To be honest I don't know why we used `HDF5_DEPENDENCIES` for `silo` and `conduit` targets as opposed to just writing `DEPENDS hdf5`. HDF5 a non-optional dependency and that var always get set to just `hdf5`. Perhaps there were multiple targets to depend on at some point but that got changed later? Up to you if you want to keep it this way for consistency, or change to
```suggestion
                        DEPENDS hdf5 minizip
```

2022-10-04 17:36 UTC, klevzoff commented on CMakeLists.txt
> +if( ENABLE_VTK AND ENABLE_FESAPI )
Though I understand the intent to save build time, I would maybe not encode it here that VTK is currently required for FESAPI to be usable in the main code. There's no formal dependency in the build process, and it's something that GEOSX configuration should handle (and probably does in your GEOSX branch), but as far as building TPLs those could be enabled independently.
```suggestion
if( ENABLE_FESAPI )
```

2022-10-04 17:42 UTC, klevzoff commented
> Where can I enable the ENABLE_FESAPI flag to the CI to compile it ?

I would suggest just adding an option 
```
option( ENABLE_FESAPI "" ON )
```
next to [these] (https://github.com/GEOSX/thirdPartyLibs/blob/1e7c6ea5717385c81973195fe588e7c5d636e0c3/CMakeLists.txt#L53) lines.

I'm ok with this being on by default, assuming no build issues come up on any of the platforms (LC and TotalEnergies clusters). If they do come up, we'll change the default to `OFF` and explicitly enable it in [default host-config](https://github.com/GEOSX/thirdPartyLibs/blob/1e7c6ea5717385c81973195fe588e7c5d636e0c3/host-configs/environment.cmake) and [Travis config](https://github.com/GEOSX/thirdPartyLibs/blob/1e7c6ea5717385c81973195fe588e7c5d636e0c3/.travis.yml)

2022-10-06 08:32 UTC, untereiner commented on CMakeLists.txt
> +if( ENABLE_VTK AND ENABLE_FESAPI )
Ok I agree

2022-10-10 09:51 UTC, philippeVerney commented on CMakeLists.txt
> +                                    -DWITH_ETP:BOOL=ON
This variable is no more available in FESAPI v2.3.0.0

2022-10-10 09:51 UTC, philippeVerney commented on CMakeLists.txt
> +    # Then Fesapi
Boost should be installed.
Latest version would be the best choice but 1.44.0 is minimal required version and 1.67.0 is recommended minimal version.

2022-10-10 11:56 UTC, untereiner commented on CMakeLists.txt
> +    # Then Fesapi
Ok, I was thinking it should be a system dependency. I will add it.

2022-10-10 12:11 UTC, untereiner commented on CMakeLists.txt
> +    # Then Fesapi
Should I download / build / install boost ? or try to unzip it in the build directory for the headers ?

2022-10-10 13:20 UTC, philippeVerney commented on CMakeLists.txt
> +    # Then Fesapi
I am pretty that boost headers are sufficient for FESAPI (at least I am sure on windows so I guess the same on Linux).
My recommendation would be to follow your latest option : "try to unzip it in the build directory for the headers"
I hope the findPackage(Boost REQUIRED) of FESAPI CMakeLists will not complain (it should not since no boost library is needed). However, in order to confirm, a first local try before to push on the CI would be suitable.

2022-10-10 14:00 UTC, untereiner commented on CMakeLists.txt
> +    # Then Fesapi
A CMale OS independent [extract](https://cmake.org/cmake/help/v3.18/command/file.html#archive-extract) function is only available starting from version 3.18. In this project:
`cmake_minimum_required(VERSION 3.9)`

2022-10-10 14:28 UTC, philippeVerney commented on CMakeLists.txt
> +    # Then Fesapi
Let's explore if ExternalProject_Add could do the extract without configure/build and install.

2022-10-20 21:48 UTC, rrsettgast commented
@TotoGaz 
Even though we disabled trillions, looks like the brew update will lead to running out of time again.

2022-10-20 23:58 UTC, TotoGaz commented
The thing is that I did not find any way to fix the `brew` issue.
And I don't use `brew` so I can only copy/paste recipes from the web.
One solution that I can see is to test using the `open-mpi` version officially in sync which is `4.1.4` instead of `4.1.1` we have actually?

2022-10-21 19:16 UTC, untereiner commented
Maybe a brew update or update the macOS image ?

2022-10-21 22:33 UTC, TotoGaz commented
> Maybe a brew update or update the macOS image ?

If you manage to make it work it's perfect.
Or simply don't build it on MacOSX

2022-10-26 01:16 UTC, TotoGaz requested changes

2022-10-26 01:16 UTC, TotoGaz commented on .travis.yml
> +  - GEOSX_DIR=/usr/local/GEOSX
It's not required that `GEOSX_TPL_DIR` is an `env` variable.
Please let it defined as a simple variable.
Plus `GEOSX_DIR` is not an `env` variable either.
And it's not `/usr/local/GEOSX`, it's `${GEOSX_TPL_DIR}/..`.
Furthermore, it's used once so you may not need to define a variable for it?

2022-10-26 01:16 UTC, TotoGaz commented on .travis.yml
> +  #- brew upgrade python@3.9
Please remove the commented code.
Please change the comment line 27 which is no more relevant.

2022-10-26 06:27 UTC, untereiner commented on .travis.yml
> +  - GEOSX_DIR=/usr/local/GEOSX
Actually I do not understand the use of the recursive folder creation switch and giving to mkdir the parent dir... Even more it seems that the python script can not delete the GEOSX_TPL folder, even with all rights
```
[config-build.py]:[INFO]: Creating install path '/usr/local/GEOSX/GEOSX_TPL'...
Traceback (most recent call last):
  File "/Users/travis/build/GEOSX/thirdPartyLibs/scripts/config-build.py", line 213, in <module>
    main(sys.argv[0], *parse_args(sys.argv[1:]))
  File "/Users/travis/build/GEOSX/thirdPartyLibs/scripts/config-build.py", line 161, in main
    os.makedirs(install_path)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/GEOSX'
```

2022-10-26 06:28 UTC, untereiner commented on .travis.yml
> +  - python3 scripts/config-build.py -hc ${TRAVIS_BUILD_DIR}/host-configs/darwin-clang.cmake -bt Release -ip ${GEOSX_TPL_DIR} -DNUM_PROC=$(nproc) -DGEOSXTPL_ENABLE_DOXYGEN:BOOL=OFF -DENABLE_VTK:BOOL=O
I can reactive it and try

2022-10-26 06:28 UTC, untereiner commented on .travis.yml
> +  #- brew upgrade python@3.9
ok

2022-10-26 09:55 UTC, untereiner commented on .travis.yml
> +  - python3 scripts/config-build.py -hc ${TRAVIS_BUILD_DIR}/host-configs/darwin-clang.cmake -bt Release -ip ${GEOSX_TPL_DIR} -DNUM_PROC=$(nproc) -DGEOSXTPL_ENABLE_DOXYGEN:BOOL=OFF -DENABLE_VTK:BOOL=O
trilinos is too expensive

2022-10-26 11:28 UTC, untereiner commented on .travis.yml
> +  - GEOSX_DIR=/usr/local/GEOSX
I removed the variables from the environment

2022-10-26 15:59 UTC, TotoGaz commented on .travis.yml
> +  - GEOSX_DIR=/usr/local/GEOSX
I don't get your error. Does this happen with the previous script?
Also, why would it delete something? And the error code looks like the script fails at creating a folder, not deleting?
And sometimes with mac osx there may be [some extended permissions](https://en.wikipedia.org/wiki/System_Integrity_Protection) that I do not fully understand.
So most probably the previous code does a trick to deal with this.

2022-10-27 12:41 UTC, untereiner commented
The CI is green. I think it is ready to be merged

2022-10-27 12:51 UTC, untereiner commented on .travis.yml
> +  - GEOSX_DIR=/usr/local/GEOSX
Sorry, too many builds. The error with the previous script is this one:
```
$ GEOSX_TPL_DIR=/usr/local/GEOSX/GEOSX_TPL && sudo mkdir -p -m a=rwx ${GEOSX_TPL_DIR}/..
....
....
[config-build.py]:[INFO]: Install directory '/usr/local/GEOSX/GEOSX_TPL' already exists. Deleting...
Traceback (most recent call last):
  File "/Users/travis/build/GEOSX/thirdPartyLibs/scripts/config-build.py", line 213, in <module>
    main(sys.argv[0], *parse_args(sys.argv[1:]))
  File "/Users/travis/build/GEOSX/thirdPartyLibs/scripts/config-build.py", line 158, in main
    shutil.rmtree(install_path)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 740, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 738, in rmtree
    os.rmdir(path)
PermissionError: [Errno 13] Permission denied: '/usr/local/GEOSX/GEOSX_TPL'
```

It will delete something because the lines 135-137 in config-build.py:
```
    if os.path.exists(build_path):
        logging.info("Build directory '%s' already exists. Deleting..." % build_path)
        shutil.rmtree(build_path)
```

Since I updated the macos image to update the homebrew db the permission management may have changed since with this version.
I guess their are somehow far fetched permissions on macos.

2022-10-27 18:15 UTC, TotoGaz commented on .travis.yml
> +  - GEOSX_DIR=/usr/local/GEOSX
Well, I do not know the whole story, but as a first element, `/usr/local/GEOSX/GEOSX_TP` should not be already created.

2022-10-27 21:52 UTC, TotoGaz commented
> The CI is green. I think it is ready to be merged

This PR does not seem to build GEOSX?

2022-11-02 08:19 UTC, untereiner commented
Yet it does !

2022-11-03 15:51 UTC, TotoGaz approved these changes

2022-11-08 22:17 UTC, merged

2023-09-15 14:49 UTC, paveltomin commented
@TotoGaz @rrsettgast should we drop fesapi from tpl since the PR on GEOS side got abandoned?

2023-09-16 12:52 UTC, untereiner commented
Hello @paveltomin, if you don’t use it, don’t compile it.. by the way to make it work an update was requested #213